content: config-server-content

management:
  security:
    enabled: false

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/  #,http://peer2:8762/eureka/,http://peer3:8763/eureka/
---
#rabbitMQ
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


content: config-server-content