---
#profile set
spring:
  profiles:
    include: dev
content: zuul2
---
#router set
zuul:
  routes:
    eureka-provider-service:
      path: /providerApi/**
      serviceId: eureka-provider-service
    eureka-consumer-service:
      path: /consumerApi/**
      serviceId: eureka-consumer-service


---
#rabbitMQ
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
---
# retry
spring:
  cloud:
    config:
      retry:
        #retry count
        max-attempts: 3
        multiplier: 1.1
        #init for retry time
        initial-interval: 1000
        #max interval for retry time
        max-interval: 2000
