spring:
  profiles:
    include: dev

zuul:
  routes:
    eureka-provider-service:
      path: /providerApi/**
      serviceId: eureka-provider-service
    eureka-consumer-service:
      path: /consumerApi/**
      serviceId: eureka-consumer-service