spring:
  profiles:
    include: prod
---
zuul:
  routes:
    eureka-provider-service:
      path: /providerApi/**
      serviceId: eureka-provider-service
    eureka-consumer-service:
      path: /consumerApi/**
      serviceId: eureka-consumer-service


---
#rabbitMQ
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest